#!/bin/bash
#SBATCH -p gpu_short
#SBATCH --gres=gpu:1
##SBATCH --cpus-per-task=52
#SBATCH -n 1
#SBATCH -t 4:00:00
#SBATCH -J ORB2_FC_SUPER
#SBATCH --output=output_script/%x-%j.out
#SBATCH --error=output_script/%x-%j.err

set -euo pipefail

mkdir -p output_script
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

nvidia-smi || true
module avail cuda || true

date

source ~/miniconda3/etc/profile.d/conda.sh
conda activate hacknip

PY_SCRIPT="src/matbench/featurize_construct_from_supercells.py"
DATA_ROOT="/work/y-tomiya/ntu/HackNIP_master/HackNIP/benchmark_data"
SLUG="ood_split_dedup_w_min_freq"
MLIP="orb2"
MODEL="modnet"
DEVICE="auto"

STRUCTURES_DIR="${DATA_ROOT}/structures"
METADATA_DIR="${DATA_ROOT}/metadata"
STRUCTURES_PATH="${STRUCTURES_DIR}/${SLUG}_all_XPS.traj"
META_PATH="${METADATA_DIR}/${SLUG}_meta.pkl"

if [[ ! -f "${STRUCTURES_PATH}" ]]; then
  echo "[ERROR] Missing supercell trajectory: ${STRUCTURES_PATH}" >&2
  exit 1
fi
if [[ ! -f "${META_PATH}" ]]; then
  echo "[ERROR] Missing metadata pickle: ${META_PATH}" >&2
  exit 1
fi

# Detect optional per-split metadata/trajectory bundles generated by build_supercells_from_pkl.py
declare -a SPLITS=()
for split_meta in "${METADATA_DIR}/${SLUG}"_*_meta.pkl; do
  [[ "${split_meta}" == "${META_PATH}" ]] && continue
  [[ ! -f "${split_meta}" ]] && continue
  split_name="${split_meta##*/}"
  split_name="${split_name#${SLUG}_}"
  split_name="${split_name%_meta.pkl}"
  SPLITS+=("${split_name}")
done

if (( ${#SPLITS[@]} > 0 )); then
  echo "[INFO] Detected split metadata: ${SPLITS[*]}"
  for split in "${SPLITS[@]}"; do
    split_traj="${STRUCTURES_DIR}/${SLUG}_${split}_XPS.traj"
    if [[ ! -f "${split_traj}" ]]; then
      echo "[ERROR] Missing supercell trajectory for split '${split}': ${split_traj}" >&2
      exit 1
    fi
    split_meta_path="${METADATA_DIR}/${SLUG}_${split}_meta.pkl"
    if [[ ! -f "${split_meta_path}" ]]; then
      echo "[ERROR] Missing metadata for split '${split}': ${split_meta_path}" >&2
      exit 1
    fi
  done
else
  echo "[INFO] No per-split metadata detected (will build aggregate bundle only)."
fi

mkdir -p "$(dirname "${STRUCTURES_PATH}")"
mkdir -p "$(dirname "${META_PATH}")"

echo "[INFO] DATA_ROOT=${DATA_ROOT}"
echo "[INFO] STRUCTURES_DIR=${STRUCTURES_DIR}"
echo "[INFO] METADATA_DIR=${METADATA_DIR}"
echo "[INFO] SLUG=${SLUG}"
echo "[INFO] MLIP=${MLIP}, MODEL=${MODEL}"
echo "[INFO] DEVICE=${DEVICE}"
echo "[INFO] PY_SCRIPT=${PY_SCRIPT}"

CMD=( python "${PY_SCRIPT}"
  --slug "${SLUG}"
  --data-root "${DATA_ROOT}"
  --mlip "${MLIP}"
  --model "${MODEL}"
  --device "${DEVICE}"
  # --overwrite
)

echo "[INFO] Command: ${CMD[*]}"

srun --cpu-bind=cores "${CMD[@]}"

date
